version: "3.7"

services:
  api:
    build: ./api
    volumes:
      - ./api:/usr/src/app
    ports:
      - "5000:5000"
    environment:
      MONGO_HOST: api-db
      MONGO_PORT: 27017
      ENDPOINT: "http://localhost:5000/graphql"
      SUBSCRIPTION_ENDPOINT: "ws://localhost:5000/graphql"
    depends_on:
      - api-db

  api-db:
    image: mongo
    command: "mongod --auth"
    volumes:
      - api-db-data:/data/db
    ports:
      - "27017:27017"
    restart: always

volumes:
  api-db-data:
