version: "3.7"

x-variables:
  - &api-db-port 27017
  - &api-db-username root
  - &api-db-password ${MONGO_PASSWORD}

services:
  api:
    build: ./api
    volumes:
      - ./api:/usr/src/app
    ports:
      - "5000:5000"
    environment:
      MONGO_HOST: api-db
      MONGO_PORT: 27017
      ENDPOINT: "http://localhost:5000/graphql"
      SUBSCRIPTION_ENDPOINT: "ws://localhost:5000/graphql"
    depends_on:
      - api-db

  api-db:
    image: mongo
    volumes:
      - api-db-data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: *api-db-username
      MONGO_INITDB_ROOT_PASSWORD: *api-db-password
    restart: always

volumes:
  api-db-data:
