version: "3"

services:
  api:
    container_name: api
    restart: always
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 5000:3000
    links:
      - database
    depends_on:
      - database

  database:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27018:27017"
