version: "3.7"

services:
  api:
    build: ./api
    volumes:
      - ./api:/usr/src/app
    ports:
      - "5000:5000"
    environment:
      MONGO_HOST: api-db
      MONGO_PORT: 27017
      PUBLISHED_HOST: "localhost"
    depends_on:
      - api-db

  api-db:
    image: mongo
    volumes:
      - api-db-data
    ports:
      - "27017:27017"
    restart: always

volumes:
  api-db-data:
