version: "3"

services:
  api:
    container_name: superorch-api
    restart: always
    build: ./api
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 5000:5000
    environment: 
      VIRTUAL_HOST: 'localhost'
      VIRTUAL_PORT: '5000'
    links:
      - database
    depends_on:
      - database

  database:
    image: mongo
    container_name: superorch-db
    restart: always
    ports:
      - "27017:27017"
