version: "3"

services:
  api:
    container_name: superorch-api
    restart: always
    build: ./
    volumes:
      - .:/usr/src/app
    ports:
      - 5000:3000
    environment: 
      PUBLISHED_PORT: 5000
      TARGET_PORT: 3000
    links:
      - database
    depends_on:
      - database

  database:
    image: mongo
    container_name: superorch-db
    restart: always
    ports:
      - "27018:27017"
