version: "3"

services:
  api:
    container_name: superorch-api
    restart: always
    build: ./
    ports:
      - 80:3000
    links:
      - database
    depends_on:
      - database

  database:
    image: mongo
    container_name: superorch-db
    restart: always
    ports:
      - "27017:27017"
