version: "3.7"

services:
  api:
    image: eu.gcr.io/lorenzorivosecchi/superorch_api
    environment:
      MONGO_HOST: superorch_db
      MONGO_PORT: 27017
      ENDPOINT: "https://superorch-api.lorenzorivosecchi.com/graphql"
      SUBSCRIPTION_ENDPOINT: "ws://superorch-api.lorenzorivosecchi.com/graphql"
    depends_on:
      - db
    deploy:
      labels:
        # Explicitly tell Traefik to expose this container
        - "traefik.enable=true"
        # Get the routes from http
        - "traefik.http.routers.superorch-api.rule=Host(`superorch-api.lorenzorivosecchi.com`)"
        - "traefik.http.routers.superorch-api.entrypoints=web"
        # Redirect these routes to https
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
        - "traefik.http.routers.superorch-api.middlewares=redirect-to-https"
        # Get the routes from https
        - "traefik.http.routers.superorch-api-secure.rule=Host(`superorch-api.lorenzorivosecchi.com`)"
        - "traefik.http.routers.superorch-api-secure.entrypoints=websecure"
        - "traefik.http.routers.superorch-api-secure.tls=true"
        - "traefik.http.routers.superorch-api-secure.tls.certresolver=myresolver"
        # Specify the port to use for communication
        - "traefik.http.services.superorch-api.loadbalancer.server.port=5000"
    networks:
      - lorenzo-proxy-net

  db:
    image: mongo
    volumes:
      - db-data:/data/db
    networks:
      - lorenzo-proxy-net

volumes:
  db-data:

networks:
  lorenzo-proxy-net:
    external: true
